language: ruby

services:
  - mysql

rvm:
  - 2.3.1

env:
  - REDMINE_VER=3.4.6

before_install:
  - export PLUGIN_NAME=redmine_my_page_queries
  - export DB=mysql
  - export REDMINE_PATH=$HOME/redmine
  - svn co http://svn.redmine.org/redmine/tags/$REDMINE_VER $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database-$DB-travis.yml $REDMINE_PATH/config/database.yml
  - cd $REDMINE_PATH

before_script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:migrate

script:
  - export RAILS_ENV=test
  - export RUBYOPT="-W0"
  - bundle exec rake redmine:plugins:test NAME=$PLUGIN_NAME
